/**
 * engineering-metadata.ts
 * 
 * Strict Metadata for Engineering Functions
 * 
 * Classification Rules:
 * - Base conversion: O(1), EXACT precision
 * - Bitwise operations: O(1), EXACT (integer operations)
 * - Complex number operations: O(1), EXACT (IEEE 754)
 * - All use PROPAGATE_FIRST error strategy
 */

import { 
  FunctionCategory,
  ComplexityClass,
  PrecisionClass,
  ErrorStrategy,
  type StrictFunctionMetadata 
} from '../../types/formula-types';
import * as EngineeringFunctions from '../engineering';

/**
 * Engineering Category: Strict Metadata
 * 
 * Total Functions: 43
 * Subcategories:
 * - Base Conversion: 12 functions (BIN2*, DEC2*, HEX2*, OCT2*)
 * - Bitwise: 5 functions (BITAND, BITOR, BITXOR, BITLSHIFT, BITRSHIFT)
 * - Complex Numbers: 26 functions (COMPLEX, IM*)
 */

export const ENGINEERING_METADATA: StrictFunctionMetadata[] = [
  // ============================================================================
  // BASE CONVERSION FUNCTIONS
  // ============================================================================
  
  {
    name: 'BIN2DEC',
    handler: EngineeringFunctions.BIN2DEC,
    category: FunctionCategory.ENGINEERING,
    minArgs: 1,
    maxArgs: 1,
    isSpecial: false,
    needsContext: false,
    volatile: false,
    complexityClass: ComplexityClass.O_1,
    precisionClass: PrecisionClass.EXACT,
    errorStrategy: ErrorStrategy.PROPAGATE_FIRST,
    iterationPolicy: null,
  },
  
  {
    name: 'BIN2HEX',
    handler: EngineeringFunctions.BIN2HEX,
    category: FunctionCategory.ENGINEERING,
    minArgs: 1,
    maxArgs: 2,
    isSpecial: false,
    needsContext: false,
    volatile: false,
    complexityClass: ComplexityClass.O_1,
    precisionClass: PrecisionClass.EXACT,
    errorStrategy: ErrorStrategy.PROPAGATE_FIRST,
    iterationPolicy: null,
  },
  
  {
    name: 'BIN2OCT',
    handler: EngineeringFunctions.BIN2OCT,
    category: FunctionCategory.ENGINEERING,
    minArgs: 1,
    maxArgs: 2,
    isSpecial: false,
    needsContext: false,
    volatile: false,
    complexityClass: ComplexityClass.O_1,
    precisionClass: PrecisionClass.EXACT,
    errorStrategy: ErrorStrategy.PROPAGATE_FIRST,
    iterationPolicy: null,
  },
  
  {
    name: 'DEC2BIN',
    handler: EngineeringFunctions.DEC2BIN,
    category: FunctionCategory.ENGINEERING,
    minArgs: 1,
    maxArgs: 2,
    isSpecial: false,
    needsContext: false,
    volatile: false,
    complexityClass: ComplexityClass.O_1,
    precisionClass: PrecisionClass.EXACT,
    errorStrategy: ErrorStrategy.PROPAGATE_FIRST,
    iterationPolicy: null,
  },
  
  {
    name: 'DEC2HEX',
    handler: EngineeringFunctions.DEC2HEX,
    category: FunctionCategory.ENGINEERING,
    minArgs: 1,
    maxArgs: 2,
    isSpecial: false,
    needsContext: false,
    volatile: false,
    complexityClass: ComplexityClass.O_1,
    precisionClass: PrecisionClass.EXACT,
    errorStrategy: ErrorStrategy.PROPAGATE_FIRST,
    iterationPolicy: null,
  },
  
  {
    name: 'DEC2OCT',
    handler: EngineeringFunctions.DEC2OCT,
    category: FunctionCategory.ENGINEERING,
    minArgs: 1,
    maxArgs: 2,
    isSpecial: false,
    needsContext: false,
    volatile: false,
    complexityClass: ComplexityClass.O_1,
    precisionClass: PrecisionClass.EXACT,
    errorStrategy: ErrorStrategy.PROPAGATE_FIRST,
    iterationPolicy: null,
  },
  
  {
    name: 'HEX2BIN',
    handler: EngineeringFunctions.HEX2BIN,
    category: FunctionCategory.ENGINEERING,
    minArgs: 1,
    maxArgs: 2,
    isSpecial: false,
    needsContext: false,
    volatile: false,
    complexityClass: ComplexityClass.O_1,
    precisionClass: PrecisionClass.EXACT,
    errorStrategy: ErrorStrategy.PROPAGATE_FIRST,
    iterationPolicy: null,
  },
  
  {
    name: 'HEX2DEC',
    handler: EngineeringFunctions.HEX2DEC,
    category: FunctionCategory.ENGINEERING,
    minArgs: 1,
    maxArgs: 1,
    isSpecial: false,
    needsContext: false,
    volatile: false,
    complexityClass: ComplexityClass.O_1,
    precisionClass: PrecisionClass.EXACT,
    errorStrategy: ErrorStrategy.PROPAGATE_FIRST,
    iterationPolicy: null,
  },
  
  {
    name: 'HEX2OCT',
    handler: EngineeringFunctions.HEX2OCT,
    category: FunctionCategory.ENGINEERING,
    minArgs: 1,
    maxArgs: 2,
    isSpecial: false,
    needsContext: false,
    volatile: false,
    complexityClass: ComplexityClass.O_1,
    precisionClass: PrecisionClass.EXACT,
    errorStrategy: ErrorStrategy.PROPAGATE_FIRST,
    iterationPolicy: null,
  },
  
  {
    name: 'OCT2BIN',
    handler: EngineeringFunctions.OCT2BIN,
    category: FunctionCategory.ENGINEERING,
    minArgs: 1,
    maxArgs: 2,
    isSpecial: false,
    needsContext: false,
    volatile: false,
    complexityClass: ComplexityClass.O_1,
    precisionClass: PrecisionClass.EXACT,
    errorStrategy: ErrorStrategy.PROPAGATE_FIRST,
    iterationPolicy: null,
  },
  
  {
    name: 'OCT2DEC',
    handler: EngineeringFunctions.OCT2DEC,
    category: FunctionCategory.ENGINEERING,
    minArgs: 1,
    maxArgs: 1,
    isSpecial: false,
    needsContext: false,
    volatile: false,
    complexityClass: ComplexityClass.O_1,
    precisionClass: PrecisionClass.EXACT,
    errorStrategy: ErrorStrategy.PROPAGATE_FIRST,
    iterationPolicy: null,
  },
  
  {
    name: 'OCT2HEX',
    handler: EngineeringFunctions.OCT2HEX,
    category: FunctionCategory.ENGINEERING,
    minArgs: 1,
    maxArgs: 2,
    isSpecial: false,
    needsContext: false,
    volatile: false,
    complexityClass: ComplexityClass.O_1,
    precisionClass: PrecisionClass.EXACT,
    errorStrategy: ErrorStrategy.PROPAGATE_FIRST,
    iterationPolicy: null,
  },
  
  // ============================================================================
  // BITWISE FUNCTIONS
  // ============================================================================
  
  {
    name: 'BITAND',
    handler: EngineeringFunctions.BITAND,
    category: FunctionCategory.ENGINEERING,
    minArgs: 2,
    maxArgs: 2,
    isSpecial: false,
    needsContext: false,
    volatile: false,
    complexityClass: ComplexityClass.O_1,
    precisionClass: PrecisionClass.EXACT,
    errorStrategy: ErrorStrategy.PROPAGATE_FIRST,
    iterationPolicy: null,
  },
  
  {
    name: 'BITOR',
    handler: EngineeringFunctions.BITOR,
    category: FunctionCategory.ENGINEERING,
    minArgs: 2,
    maxArgs: 2,
    isSpecial: false,
    needsContext: false,
    volatile: false,
    complexityClass: ComplexityClass.O_1,
    precisionClass: PrecisionClass.EXACT,
    errorStrategy: ErrorStrategy.PROPAGATE_FIRST,
    iterationPolicy: null,
  },
  
  {
    name: 'BITXOR',
    handler: EngineeringFunctions.BITXOR,
    category: FunctionCategory.ENGINEERING,
    minArgs: 2,
    maxArgs: 2,
    isSpecial: false,
    needsContext: false,
    volatile: false,
    complexityClass: ComplexityClass.O_1,
    precisionClass: PrecisionClass.EXACT,
    errorStrategy: ErrorStrategy.PROPAGATE_FIRST,
    iterationPolicy: null,
  },
  
  {
    name: 'BITLSHIFT',
    handler: EngineeringFunctions.BITLSHIFT,
    category: FunctionCategory.ENGINEERING,
    minArgs: 2,
    maxArgs: 2,
    isSpecial: false,
    needsContext: false,
    volatile: false,
    complexityClass: ComplexityClass.O_1,
    precisionClass: PrecisionClass.EXACT,
    errorStrategy: ErrorStrategy.PROPAGATE_FIRST,
    iterationPolicy: null,
  },
  
  {
    name: 'BITRSHIFT',
    handler: EngineeringFunctions.BITRSHIFT,
    category: FunctionCategory.ENGINEERING,
    minArgs: 2,
    maxArgs: 2,
    isSpecial: false,
    needsContext: false,
    volatile: false,
    complexityClass: ComplexityClass.O_1,
    precisionClass: PrecisionClass.EXACT,
    errorStrategy: ErrorStrategy.PROPAGATE_FIRST,
    iterationPolicy: null,
  },
  
  // ============================================================================
  // COMPLEX NUMBER FUNCTIONS
  // ============================================================================
  
  {
    name: 'COMPLEX',
    handler: EngineeringFunctions.COMPLEX,
    category: FunctionCategory.ENGINEERING,
    minArgs: 2,
    maxArgs: 3,
    isSpecial: false,
    needsContext: false,
    volatile: false,
    complexityClass: ComplexityClass.O_1,
    precisionClass: PrecisionClass.EXACT,
    errorStrategy: ErrorStrategy.PROPAGATE_FIRST,
    iterationPolicy: null,
  },
  
  {
    name: 'IMREAL',
    handler: EngineeringFunctions.IMREAL,
    category: FunctionCategory.ENGINEERING,
    minArgs: 1,
    maxArgs: 1,
    isSpecial: false,
    needsContext: false,
    volatile: false,
    complexityClass: ComplexityClass.O_1,
    precisionClass: PrecisionClass.EXACT,
    errorStrategy: ErrorStrategy.PROPAGATE_FIRST,
    iterationPolicy: null,
  },
  
  {
    name: 'IMAGINARY',
    handler: EngineeringFunctions.IMAGINARY,
    category: FunctionCategory.ENGINEERING,
    minArgs: 1,
    maxArgs: 1,
    isSpecial: false,
    needsContext: false,
    volatile: false,
    complexityClass: ComplexityClass.O_1,
    precisionClass: PrecisionClass.EXACT,
    errorStrategy: ErrorStrategy.PROPAGATE_FIRST,
    iterationPolicy: null,
  },
  
  {
    name: 'IMABS',
    handler: EngineeringFunctions.IMABS,
    category: FunctionCategory.ENGINEERING,
    minArgs: 1,
    maxArgs: 1,
    isSpecial: false,
    needsContext: false,
    volatile: false,
    complexityClass: ComplexityClass.O_1,
    precisionClass: PrecisionClass.EXACT,
    errorStrategy: ErrorStrategy.PROPAGATE_FIRST,
    iterationPolicy: null,
  },
  
  {
    name: 'IMARGUMENT',
    handler: EngineeringFunctions.IMARGUMENT,
    category: FunctionCategory.ENGINEERING,
    minArgs: 1,
    maxArgs: 1,
    isSpecial: false,
    needsContext: false,
    volatile: false,
    complexityClass: ComplexityClass.O_1,
    precisionClass: PrecisionClass.EXACT,
    errorStrategy: ErrorStrategy.PROPAGATE_FIRST,
    iterationPolicy: null,
  },
  
  {
    name: 'IMCONJUGATE',
    handler: EngineeringFunctions.IMCONJUGATE,
    category: FunctionCategory.ENGINEERING,
    minArgs: 1,
    maxArgs: 1,
    isSpecial: false,
    needsContext: false,
    volatile: false,
    complexityClass: ComplexityClass.O_1,
    precisionClass: PrecisionClass.EXACT,
    errorStrategy: ErrorStrategy.PROPAGATE_FIRST,
    iterationPolicy: null,
  },
  
  {
    name: 'IMADD',
    handler: EngineeringFunctions.IMADD,
    category: FunctionCategory.ENGINEERING,
    minArgs: 2,
    maxArgs: 2,
    isSpecial: false,
    needsContext: false,
    volatile: false,
    complexityClass: ComplexityClass.O_1,
    precisionClass: PrecisionClass.EXACT,
    errorStrategy: ErrorStrategy.PROPAGATE_FIRST,
    iterationPolicy: null,
  },
  
  {
    name: 'IMSUB',
    handler: EngineeringFunctions.IMSUB,
    category: FunctionCategory.ENGINEERING,
    minArgs: 2,
    maxArgs: 2,
    isSpecial: false,
    needsContext: false,
    volatile: false,
    complexityClass: ComplexityClass.O_1,
    precisionClass: PrecisionClass.EXACT,
    errorStrategy: ErrorStrategy.PROPAGATE_FIRST,
    iterationPolicy: null,
  },
  
  {
    name: 'IMMULT',
    handler: EngineeringFunctions.IMMULT,
    category: FunctionCategory.ENGINEERING,
    minArgs: 2,
    maxArgs: 2,
    isSpecial: false,
    needsContext: false,
    volatile: false,
    complexityClass: ComplexityClass.O_1,
    precisionClass: PrecisionClass.EXACT,
    errorStrategy: ErrorStrategy.PROPAGATE_FIRST,
    iterationPolicy: null,
  },
  
  {
    name: 'IMDIV',
    handler: EngineeringFunctions.IMDIV,
    category: FunctionCategory.ENGINEERING,
    minArgs: 2,
    maxArgs: 2,
    isSpecial: false,
    needsContext: false,
    volatile: false,
    complexityClass: ComplexityClass.O_1,
    precisionClass: PrecisionClass.EXACT,
    errorStrategy: ErrorStrategy.PROPAGATE_FIRST,
    iterationPolicy: null,
  },
  
  {
    name: 'IMPOWER',
    handler: EngineeringFunctions.IMPOWER,
    category: FunctionCategory.ENGINEERING,
    minArgs: 2,
    maxArgs: 2,
    isSpecial: false,
    needsContext: false,
    volatile: false,
    complexityClass: ComplexityClass.O_1,
    precisionClass: PrecisionClass.EXACT,
    errorStrategy: ErrorStrategy.PROPAGATE_FIRST,
    iterationPolicy: null,
  },
  
  {
    name: 'IMSQRT',
    handler: EngineeringFunctions.IMSQRT,
    category: FunctionCategory.ENGINEERING,
    minArgs: 1,
    maxArgs: 1,
    isSpecial: false,
    needsContext: false,
    volatile: false,
    complexityClass: ComplexityClass.O_1,
    precisionClass: PrecisionClass.EXACT,
    errorStrategy: ErrorStrategy.PROPAGATE_FIRST,
    iterationPolicy: null,
  },
  
  {
    name: 'IMEXP',
    handler: EngineeringFunctions.IMEXP,
    category: FunctionCategory.ENGINEERING,
    minArgs: 1,
    maxArgs: 1,
    isSpecial: false,
    needsContext: false,
    volatile: false,
    complexityClass: ComplexityClass.O_1,
    precisionClass: PrecisionClass.EXACT,
    errorStrategy: ErrorStrategy.PROPAGATE_FIRST,
    iterationPolicy: null,
  },
  
  {
    name: 'IMLN',
    handler: EngineeringFunctions.IMLN,
    category: FunctionCategory.ENGINEERING,
    minArgs: 1,
    maxArgs: 1,
    isSpecial: false,
    needsContext: false,
    volatile: false,
    complexityClass: ComplexityClass.O_1,
    precisionClass: PrecisionClass.EXACT,
    errorStrategy: ErrorStrategy.PROPAGATE_FIRST,
    iterationPolicy: null,
  },
  
  {
    name: 'IMLOG10',
    handler: EngineeringFunctions.IMLOG10,
    category: FunctionCategory.ENGINEERING,
    minArgs: 1,
    maxArgs: 1,
    isSpecial: false,
    needsContext: false,
    volatile: false,
    complexityClass: ComplexityClass.O_1,
    precisionClass: PrecisionClass.EXACT,
    errorStrategy: ErrorStrategy.PROPAGATE_FIRST,
    iterationPolicy: null,
  },
  
  {
    name: 'IMLOG2',
    handler: EngineeringFunctions.IMLOG2,
    category: FunctionCategory.ENGINEERING,
    minArgs: 1,
    maxArgs: 1,
    isSpecial: false,
    needsContext: false,
    volatile: false,
    complexityClass: ComplexityClass.O_1,
    precisionClass: PrecisionClass.EXACT,
    errorStrategy: ErrorStrategy.PROPAGATE_FIRST,
    iterationPolicy: null,
  },
  
  {
    name: 'IMSIN',
    handler: EngineeringFunctions.IMSIN,
    category: FunctionCategory.ENGINEERING,
    minArgs: 1,
    maxArgs: 1,
    isSpecial: false,
    needsContext: false,
    volatile: false,
    complexityClass: ComplexityClass.O_1,
    precisionClass: PrecisionClass.EXACT,
    errorStrategy: ErrorStrategy.PROPAGATE_FIRST,
    iterationPolicy: null,
  },
  
  {
    name: 'IMCOS',
    handler: EngineeringFunctions.IMCOS,
    category: FunctionCategory.ENGINEERING,
    minArgs: 1,
    maxArgs: 1,
    isSpecial: false,
    needsContext: false,
    volatile: false,
    complexityClass: ComplexityClass.O_1,
    precisionClass: PrecisionClass.EXACT,
    errorStrategy: ErrorStrategy.PROPAGATE_FIRST,
    iterationPolicy: null,
  },
  
  {
    name: 'IMTAN',
    handler: EngineeringFunctions.IMTAN,
    category: FunctionCategory.ENGINEERING,
    minArgs: 1,
    maxArgs: 1,
    isSpecial: false,
    needsContext: false,
    volatile: false,
    complexityClass: ComplexityClass.O_1,
    precisionClass: PrecisionClass.EXACT,
    errorStrategy: ErrorStrategy.PROPAGATE_FIRST,
    iterationPolicy: null,
  },
  
  {
    name: 'IMSINH',
    handler: EngineeringFunctions.IMSINH,
    category: FunctionCategory.ENGINEERING,
    minArgs: 1,
    maxArgs: 1,
    isSpecial: false,
    needsContext: false,
    volatile: false,
    complexityClass: ComplexityClass.O_1,
    precisionClass: PrecisionClass.EXACT,
    errorStrategy: ErrorStrategy.PROPAGATE_FIRST,
    iterationPolicy: null,
  },
  
  {
    name: 'IMCOSH',
    handler: EngineeringFunctions.IMCOSH,
    category: FunctionCategory.ENGINEERING,
    minArgs: 1,
    maxArgs: 1,
    isSpecial: false,
    needsContext: false,
    volatile: false,
    complexityClass: ComplexityClass.O_1,
    precisionClass: PrecisionClass.EXACT,
    errorStrategy: ErrorStrategy.PROPAGATE_FIRST,
    iterationPolicy: null,
  },
  
  {
    name: 'IMSEC',
    handler: EngineeringFunctions.IMSEC,
    category: FunctionCategory.ENGINEERING,
    minArgs: 1,
    maxArgs: 1,
    isSpecial: false,
    needsContext: false,
    volatile: false,
    complexityClass: ComplexityClass.O_1,
    precisionClass: PrecisionClass.EXACT,
    errorStrategy: ErrorStrategy.PROPAGATE_FIRST,
    iterationPolicy: null,
  },
  
  {
    name: 'IMSECH',
    handler: EngineeringFunctions.IMSECH,
    category: FunctionCategory.ENGINEERING,
    minArgs: 1,
    maxArgs: 1,
    isSpecial: false,
    needsContext: false,
    volatile: false,
    complexityClass: ComplexityClass.O_1,
    precisionClass: PrecisionClass.EXACT,
    errorStrategy: ErrorStrategy.PROPAGATE_FIRST,
    iterationPolicy: null,
  },
  
  {
    name: 'IMCSC',
    handler: EngineeringFunctions.IMCSC,
    category: FunctionCategory.ENGINEERING,
    minArgs: 1,
    maxArgs: 1,
    isSpecial: false,
    needsContext: false,
    volatile: false,
    complexityClass: ComplexityClass.O_1,
    precisionClass: PrecisionClass.EXACT,
    errorStrategy: ErrorStrategy.PROPAGATE_FIRST,
    iterationPolicy: null,
  },
  
  {
    name: 'IMCSCH',
    handler: EngineeringFunctions.IMCSCH,
    category: FunctionCategory.ENGINEERING,
    minArgs: 1,
    maxArgs: 1,
    isSpecial: false,
    needsContext: false,
    volatile: false,
    complexityClass: ComplexityClass.O_1,
    precisionClass: PrecisionClass.EXACT,
    errorStrategy: ErrorStrategy.PROPAGATE_FIRST,
    iterationPolicy: null,
  },
  
  {
    name: 'IMCOT',
    handler: EngineeringFunctions.IMCOT,
    category: FunctionCategory.ENGINEERING,
    minArgs: 1,
    maxArgs: 1,
    isSpecial: false,
    needsContext: false,
    volatile: false,
    complexityClass: ComplexityClass.O_1,
    precisionClass: PrecisionClass.EXACT,
    errorStrategy: ErrorStrategy.PROPAGATE_FIRST,
    iterationPolicy: null,
  },
];
